include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: docker-container.yml

variables:
  DOCKERFILE_DIR: .
  RUN_AUTO_BUMP: ok
  AUTO_BUMP_REPO: nosana-ci/apps/platform/k8s
  AUTO_BUMP_FILE: helm-secrets.tf
  AUTO_BUMP_SCG_PREFIX: image_tag [^}]*= { dev = \"

.npm:
  image: node:18.18.2 # align with Dockerfile
  cache:
    paths:
      - node_modules
    key: $CI_COMMIT_SHORT_SHA

npm ci:
  extends: .npm
  stage: build
  script: npm ci
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

npm run lint:
  extends: .npm
  stage: test
  script: npm run lint
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
