version: '3'
services:
  nosana-secret-manager:
    image: node:18-alpine
    working_dir: /code
    command: npm run dev
    ports:
      - 4124:4124
    volumes:
      - ./:/code:cached
    environment:
      - NODE_ENV=development
      - APP_ENV=development
